package com.example.gymtracker.model.enum_classes

enum class Musculo {
    PECHO_INFERIOR,
    PECHO_SUPERIOR,
    BICEPS_CABEZA_LARGA,
    BICEPS_CABEZA_CORTA,
    TRICEPS_CABEZA_LARGA,
    TRICEPS_CABEZA_LATERAL,
    TRICEPS_CABEZA_MEDIAL,
    DORSAL_ANCHO,
    DORSAL_MEDIO,
    LUMBARES,
    CUADRICEPS,
    GEMELO,
    SOLEO,
    ISQUIOS,
    ABDUCTORES,
    DELTOIDES_ANTERIOR,
    DELTOIDES_LATERAL,
    DELTOIDES_POSTERIOR,
    BRAQUIORRADIAL,
    TRAPECIO,
    GLUTEOS,
    ABDOMINALES,
    ANTEBRAZO
}